apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gluster-storage
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://${HEKETI_URL}"
  restuser: "admin"
  restuserkey: "${admin-key}"
